language: haxe
haxe: "3.4.2"
dist: trusty
install:
  # install awscli
  - sudo apt-get install python-pip
  - sudo pip install awscli
  - aws --version
  # install haxelibs
  - yes | haxelib install all
script:
  - haxe generate.hxml && haxe deploy.hxml
