language: haxe
haxe: 
  "3.4.2"
  "development"
dist: trusty
install:
  # install awscli
  - sudo apt-get install python-pip
  - sudo pip install awscli
  - aws --version
  # install haxelibs
  - yes | haxelib install all
script:
  - haxe generate.hxml
  - if [[ "$TRAVIS_HAXE_VERSION" == "3.4.2" ]]; then haxe deploy.hxml ; fi
