language: haxe
haxe: "development"
dist: trusty
install:
  # install git lfs
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs awscli
  - git lfs init
  - git lfs pull
  # install haxelibs
  - yes | haxelib install all
script:
  - haxe generate.hxml
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: out
  upload-dir: $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = staging
after_deploy:
  - if [[ $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "staging" ]]; then
      mkdir -p ~/.aws;
      echo -e "[preview]\ncloudfront=true" >> ~/.aws/config;
      aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/$TRAVIS_BRANCH/*";
    fi
