language: haxe

haxe: 
  - "3.4.4"
  - "development"

matrix:
  allow_failures:
    - haxe: development

dist: trusty

sudo: false

install:
  # install awscli
  - pip install --user awscli
  - aws --version
  # install haxelibs
  - yes | haxelib install all

script:
  - haxe generate.hxml
  - if [[ "$TRAVIS_HAXE_VERSION" == "3.4.4" ]]; then haxe deploy.hxml ; fi
