language: haxe
haxe: "development"
dist: trusty
install:
  - yes | haxelib install all
  - haxelib git detox https://github.com/ufront/detox.git
  - haxe generateversionsjson.hxml
script:
  - haxe generate.hxml
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: out
  upload-dir: $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = staging
